export type Scheme = 'light' | 'dark';

export interface Palette {
  scheme: Scheme;
  accent: string;
  accentLight: string;
  bgTop: string;
  bgMid: string;
  bgBottom: string;
  glassBg: string;
  glassBorder: string;
  textDark: string;
  textMid: string;
  textDim: string;
}

export interface Theme {
  id: string;
  name: string;
  light: Palette;
  dark: Palette;
}

const DARK_GLASS_BG = 'rgba(255,255,255,0.06)';
const DARK_GLASS_BORDER = 'rgba(255,255,255,0.12)';
const LIGHT_GLASS_BG = 'rgba(255,255,255,0.55)';
const LIGHT_GLASS_BORDER = 'rgba(255,255,255,0.85)';

export const THEMES: Theme[] = [
  {
    id: 'sage-garden',
    name: 'Sage Garden',
    light: {
      scheme: 'light',
      accent: '#2D6A4F',
      accentLight: '#E8F5EE',
      bgTop: '#D4E8D4',
      bgMid: '#F7F3ED',
      bgBottom: '#E8F0E8',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#1A1A2E',
      textMid: '#4A5568',
      textDim: '#9AA5B4',
    },
    dark: {
      scheme: 'dark',
      accent: '#6FBF8F',
      accentLight: 'rgba(111,191,143,0.18)',
      bgTop: '#0D1B14',
      bgMid: '#14241B',
      bgBottom: '#0A1410',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#E8F0EC',
      textMid: '#B0BFB7',
      textDim: '#6E7C75',
    },
  },
  {
    id: 'midnight-mihrab',
    name: 'Midnight Mihrab',
    light: {
      scheme: 'light',
      accent: '#2C3E70',
      accentLight: '#E5EBF5',
      bgTop: '#DDE7F3',
      bgMid: '#F4F6FA',
      bgBottom: '#E2E9F1',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#14213D',
      textMid: '#4A5C7A',
      textDim: '#8E99B0',
    },
    dark: {
      scheme: 'dark',
      accent: '#7BA3E8',
      accentLight: 'rgba(123,163,232,0.18)',
      bgTop: '#08111F',
      bgMid: '#101A2E',
      bgBottom: '#060C18',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#E8EEF8',
      textMid: '#B0BBD1',
      textDim: '#6E7790',
    },
  },
  {
    id: 'desert-dawn',
    name: 'Desert Dawn',
    light: {
      scheme: 'light',
      accent: '#B8602A',
      accentLight: '#FBEFE3',
      bgTop: '#FBE5CE',
      bgMid: '#FFF7EE',
      bgBottom: '#F8E8D4',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#2A1A10',
      textMid: '#6E4F3B',
      textDim: '#B49680',
    },
    dark: {
      scheme: 'dark',
      accent: '#F0A26A',
      accentLight: 'rgba(240,162,106,0.18)',
      bgTop: '#1F1208',
      bgMid: '#2B1A0E',
      bgBottom: '#170D06',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FBEFE3',
      textMid: '#C9B5A2',
      textDim: '#7C6A58',
    },
  },
  {
    id: 'jade-mosque',
    name: 'Jade Mosque',
    light: {
      scheme: 'light',
      accent: '#0F8F87',
      accentLight: '#DEF2F0',
      bgTop: '#C9E8E5',
      bgMid: '#F1FAF8',
      bgBottom: '#DCEEEC',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#0E2A28',
      textMid: '#3F6663',
      textDim: '#8AA3A1',
    },
    dark: {
      scheme: 'dark',
      accent: '#4FCFC4',
      accentLight: 'rgba(79,207,196,0.18)',
      bgTop: '#08161A',
      bgMid: '#102528',
      bgBottom: '#060F12',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#E0F4F2',
      textMid: '#A4C0BE',
      textDim: '#66807E',
    },
  },
  {
    id: 'rose-quartz',
    name: 'Rose Quartz',
    light: {
      scheme: 'light',
      accent: '#B8456C',
      accentLight: '#FBE5EC',
      bgTop: '#F7DCE5',
      bgMid: '#FFF5F8',
      bgBottom: '#F4E0E6',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#2A101A',
      textMid: '#6E3F50',
      textDim: '#B48A99',
    },
    dark: {
      scheme: 'dark',
      accent: '#EC8AA8',
      accentLight: 'rgba(236,138,168,0.18)',
      bgTop: '#1F0A12',
      bgMid: '#2B1118',
      bgBottom: '#170609',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FBE5EC',
      textMid: '#C9A2AF',
      textDim: '#7C5862',
    },
  },
  {
    id: 'indigo-night',
    name: 'Indigo Night',
    light: {
      scheme: 'light',
      accent: '#5B3FAA',
      accentLight: '#ECE6F7',
      bgTop: '#DCD3F0',
      bgMid: '#F5F1FB',
      bgBottom: '#E5DCF1',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#1A102E',
      textMid: '#4F3F70',
      textDim: '#9489B0',
    },
    dark: {
      scheme: 'dark',
      accent: '#B49EFF',
      accentLight: 'rgba(180,158,255,0.18)',
      bgTop: '#110A1F',
      bgMid: '#1B102E',
      bgBottom: '#0B0617',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#ECE6F7',
      textMid: '#B5A8D1',
      textDim: '#6E658C',
    },
  },
  {
    id: 'olive-grove',
    name: 'Olive Grove',
    light: {
      scheme: 'light',
      accent: '#6B7A2A',
      accentLight: '#F1F4DC',
      bgTop: '#E0E5C5',
      bgMid: '#F8F8EC',
      bgBottom: '#E5E8D2',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#1F230D',
      textMid: '#4F5530',
      textDim: '#9BA170',
    },
    dark: {
      scheme: 'dark',
      accent: '#C4D26E',
      accentLight: 'rgba(196,210,110,0.18)',
      bgTop: '#11140A',
      bgMid: '#1B1F11',
      bgBottom: '#090C05',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#F1F4DC',
      textMid: '#B7BC95',
      textDim: '#6F7459',
    },
  },
  {
    id: 'pearl-dust',
    name: 'Pearl Dust',
    light: {
      scheme: 'light',
      accent: '#5A6577',
      accentLight: '#ECEEF2',
      bgTop: '#DDE2EA',
      bgMid: '#F6F7F9',
      bgBottom: '#E4E7ED',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#1A1F2A',
      textMid: '#4A5260',
      textDim: '#99A2B0',
    },
    dark: {
      scheme: 'dark',
      accent: '#A8B5CC',
      accentLight: 'rgba(168,181,204,0.18)',
      bgTop: '#0E1116',
      bgMid: '#181C24',
      bgBottom: '#07090C',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#ECEEF2',
      textMid: '#ABB2BF',
      textDim: '#6A7280',
    },
  },
  {
    id: 'golden-sands',
    name: 'Golden Sands',
    light: {
      scheme: 'light',
      accent: '#A67C00',
      accentLight: '#FBF3DC',
      bgTop: '#F5E8B0',
      bgMid: '#FDFAF0',
      bgBottom: '#F0E5C0',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#241A00',
      textMid: '#6B5500',
      textDim: '#B8A060',
    },
    dark: {
      scheme: 'dark',
      accent: '#F0C84A',
      accentLight: 'rgba(240,200,74,0.18)',
      bgTop: '#1A1400',
      bgMid: '#261E05',
      bgBottom: '#120E00',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FBF3DC',
      textMid: '#C8B87A',
      textDim: '#7A6E40',
    },
  },
  {
    id: 'cobalt-sky',
    name: 'Cobalt Sky',
    light: {
      scheme: 'light',
      accent: '#0057B8',
      accentLight: '#E0EDFF',
      bgTop: '#C8DEFF',
      bgMid: '#F0F6FF',
      bgBottom: '#D4E6FF',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#001830',
      textMid: '#2A4E7A',
      textDim: '#7A9BBF',
    },
    dark: {
      scheme: 'dark',
      accent: '#5EA4FF',
      accentLight: 'rgba(94,164,255,0.18)',
      bgTop: '#00101F',
      bgMid: '#071A2E',
      bgBottom: '#000A16',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#E0EDFF',
      textMid: '#90B8E0',
      textDim: '#506A88',
    },
  },
  {
    id: 'crimson-dusk',
    name: 'Crimson Dusk',
    light: {
      scheme: 'light',
      accent: '#9B1C2E',
      accentLight: '#FAEAEC',
      bgTop: '#F2D0D4',
      bgMid: '#FDF5F6',
      bgBottom: '#EDD5D8',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#280810',
      textMid: '#6A2C36',
      textDim: '#B48088',
    },
    dark: {
      scheme: 'dark',
      accent: '#F07080',
      accentLight: 'rgba(240,112,128,0.18)',
      bgTop: '#1A0408',
      bgMid: '#280A10',
      bgBottom: '#110204',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#FAEAEC',
      textMid: '#C8969E',
      textDim: '#7A5058',
    },
  },
  {
    id: 'onyx',
    name: 'Onyx',
    light: {
      scheme: 'light',
      accent: '#2A2A2A',
      accentLight: '#ECECEC',
      bgTop: '#E0E0E0',
      bgMid: '#F8F8F8',
      bgBottom: '#E8E8E8',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#0A0A0A',
      textMid: '#505050',
      textDim: '#A0A0A0',
    },
    dark: {
      scheme: 'dark',
      accent: '#D0D0D0',
      accentLight: 'rgba(208,208,208,0.15)',
      bgTop: '#0A0A0A',
      bgMid: '#141414',
      bgBottom: '#050505',
      glassBg: 'rgba(255,255,255,0.05)',
      glassBorder: 'rgba(255,255,255,0.10)',
      textDark: '#F0F0F0',
      textMid: '#A8A8A8',
      textDim: '#606060',
    },
  },
  {
    id: 'mint-breeze',
    name: 'Mint Breeze',
    light: {
      scheme: 'light',
      accent: '#1A8A6E',
      accentLight: '#DFF5EF',
      bgTop: '#BEEEE2',
      bgMid: '#F0FAF7',
      bgBottom: '#CEEEE6',
      glassBg: LIGHT_GLASS_BG,
      glassBorder: LIGHT_GLASS_BORDER,
      textDark: '#082820',
      textMid: '#2E6A58',
      textDim: '#7AB0A0',
    },
    dark: {
      scheme: 'dark',
      accent: '#50D4B0',
      accentLight: 'rgba(80,212,176,0.18)',
      bgTop: '#041410',
      bgMid: '#0A201A',
      bgBottom: '#020C08',
      glassBg: DARK_GLASS_BG,
      glassBorder: DARK_GLASS_BORDER,
      textDark: '#DFF5EF',
      textMid: '#90C8B8',
      textDim: '#507868',
    },
  },
];

export const DEFAULT_THEME_ID = 'sage-garden';

export const getTheme = (id: string): Theme =>
  THEMES.find((t) => t.id === id) ?? THEMES[0];

export const glassCardStyle = (palette: Palette) =>
  ({
    backgroundColor: palette.glassBg,
    borderColor: palette.glassBorder,
    borderWidth: 1,
    borderRadius: 16,
  }) as const;
